### ISSUE TITLE
How do you transfer ownership, or sell ownership to someone?

### ISSUE THREAD

**Issue by dannydeezy** [ursuscamp/nomen#12]

**Comment by ursuscamp** [comment]
There's a story here! The current protocol (v0) originally had a transfer mechanism, but it was not well designed. There were chain of custody issues; the protocol required signed Nostr events to exist to prove ownership. This proved untenable as users would need to maintain their own "wallet" of transfer events signed by previous owners to prove the history on chain.

I went back to the drawing board and I have been working on v1. It should be ready soon. It's not much different than v0, except that you don't need to keep signed events to prove chain of custody. All of the ownership data is on chain. There not a huge size difference, it really should have been that way from the start.

Check out the v1 spec here: https://github.com/ursuscamp/nomen/blob/protocolv1/docs/SPEC.md

Caution: This is not in a release yet, and is subject to change. However it is probably only weeks away, or less.

**Comment by ursuscamp** [comment]
Also, v1 is backward compatible: v0 and v1 names share namespace, and v0 can be upgraded to v1 names if anyone who already created one ever wants to transfer them. The transition should not be noticeable to anyone.

**Comment by ursuscamp** [comment]
Transfers have been added to the protocol and are now live. It involves making two transactions (unfortunate, due to the OP_RETURN size limits). It basically requires making a "caching" transaction to cache the transfer with the new public key, and a signature transaction where the OP_RETURN output contains a matching signature from the current owner authorizing the change.

You can see more details in the official [protocol spec](https://github.com/ursuscamp/noms/blob/master/nom-02.md).

Luckily, this isn't meant to be a "transfer-heavy" protocol, unlike something like Ordinals. It's an identity protocol, so transfers should not be too common. Hopefully one day, if Nomen is popular enough, we can get some kind of special carve out to allow multiple Nomen OP_RETURNs in a single transaction.

Or Core could lift the OP_RETURN limit completely (yeah right, we can dream).

P.S. The reference indexer, Nomen Explorer, will generate the OP_RETURNs for you, and it will let you use your NIP-07 nostr extension to sign the transfer authorization. Check it out [here](https://nomenexplorer.com/transfer).
